"""Core domain models for the Cloud FinOps & Cost Optimization Agent.

These Pydantic models define the internal contract used across all layers:
MCP server, orchestrator, validation, memory, and eval harness.

Design reference: design.md Section 10.4
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, computed_field, field_validator


# ---------------------------------------------------------------------------
# Enums — constrained value sets (typo-safe, IDE-autocomplete)
# ---------------------------------------------------------------------------


class ResourceType(str, Enum):
    """Supported AWS resource types for v1."""

    EC2 = "ec2"
    RDS = "rds"
    EBS = "ebs"
    EIP = "eip"


class FindingType(str, Enum):
    """Categories of cost inefficiency the system detects."""

    IDLE = "idle"
    OVERSIZED = "oversized"
    UNUSED = "unused"
    UNTAGGED = "untagged"


class Severity(str, Enum):
    """Severity level of a finding."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class RecommendationAction(str, Enum):
    """Allowed actions the system may recommend (Section 8.3 whitelist)."""

    STOP = "stop"
    RESIZE = "resize"
    DELETE = "delete"
    REVIEW = "review"
    TAG = "tag"


class RiskLevel(str, Enum):
    """Risk level associated with a recommendation."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class ValidationStatus(str, Enum):
    """Validation state of a recommendation (Section 8.4)."""

    PENDING = "pending"
    PASSED = "passed"
    RETRIED = "retried"
    ESCALATED = "escalated"
    REJECTED = "rejected"


# ---------------------------------------------------------------------------
# Helper — UTC timestamp factory
# ---------------------------------------------------------------------------


def _utc_now() -> datetime:
    """Return current time in UTC (Section 10.10 — UTC everywhere)."""
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# Domain Models
# ---------------------------------------------------------------------------


class Resource(BaseModel):
    """An AWS resource as understood internally.

    Mapped from AWS API JSON at the MCP boundary (Section 10.3).
    This is our own contract — decoupled from AWS response shape.
    """

    model_config = ConfigDict(frozen=True)  # immutable once created

    resource_id: str = Field(..., min_length=1)
    resource_type: ResourceType
    region: str = Field(..., min_length=1)
    tags: dict[str, str] = Field(default_factory=dict)
    monthly_cost: Decimal = Field(..., ge=0)
    utilization_metrics: dict[str, float] = Field(default_factory=dict)

    @field_validator("resource_id")
    @classmethod
    def resource_id_not_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("resource_id must not be blank")
        return v

class Finding(BaseModel):
    """A detected cost inefficiency tied to a specific resource."""

    finding_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    resource_id: str = Field(..., min_length=1)
    finding_type: FindingType
    severity: Severity
    estimated_waste: Decimal = Field(..., ge=0)
    evidence: dict[str, float | int | str] = Field(default_factory=dict)


class Recommendation(BaseModel):
    """An actionable optimization step generated by the LLM.

    validation_status tracks its journey through the Validation Layer
    (Section 8.4): pending -> passed / retried / escalated / rejected.
    """

    recommendation_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    finding_id: str = Field(..., min_length=1)
    action: RecommendationAction
    rationale: str = Field(..., min_length=1)
    estimated_savings: Decimal = Field(..., ge=0)
    risk_level: RiskLevel
    priority: int = Field(..., ge=1)
    validation_status: ValidationStatus = ValidationStatus.PENDING

    @field_validator("rationale")
    @classmethod
    def rationale_not_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("rationale must not be blank")
        return v

class AuditRequest(BaseModel):
    """A request to audit a specific AWS account."""

    model_config = ConfigDict(frozen=True)  # request is immutable

    request_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    account_id: str = Field(..., min_length=1)
    session_id: str = Field(..., min_length=1)
    requested_at: datetime = Field(default_factory=_utc_now)
    audit_scope: list[ResourceType] = Field(default_factory=list)
    user_id: str | None = None


class AuditResult(BaseModel):
    """The complete output of an audit run.

    total_estimated_savings is computed from recommendations,
    not stored — prevents drift between the sum and the parts.
    """

    audit_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    request_id: str = Field(..., min_length=1)
    findings: list[Finding] = Field(default_factory=list)
    recommendations: list[Recommendation] = Field(default_factory=list)
    audit_duration_ms: int = Field(default=0, ge=0)
    llm_cost_usd: Decimal = Field(default=Decimal("0"), ge=0)
    completed_at: datetime = Field(default_factory=_utc_now)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def total_estimated_savings(self) -> Decimal:
        """Sum of savings across all recommendations (always accurate)."""
        return sum(
            (r.estimated_savings for r in self.recommendations),
            start=Decimal("0"),
        )